# Generated by Django 3.0.8 on 2020-08-07 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ada_app', '0003_auto_20200730_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyWishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='MyWhishList',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='subcategorys',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.SubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productimages',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.ProductImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='profiles',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='products',
            field=models.ManyToManyField(to='ada_app.Product'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='mywishlist',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ada_app.Product'),
        ),
        migrations.AddField(
            model_name='mywishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='myproduct',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.MyProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='myproduct',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.MyProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='myproduct',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ada_app.MyProduct'),
            preserve_default=False,
        ),
    ]
